<h1>Question 2 - Extracting Tesla Stock Data Using a Web Scraping</h1>

In [30]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

## Using Webscraping to Extract Tesla Stock Data

We will extract Tesla stock data [https://raw.githubusercontent.com/alyab16/Python-Project-for-Data-Science/cb6acd476c02df1ff74b85237a7307abf3632677/Tesla%2C%20Inc.%20(TSLA)%20Stock%20Historical%20Prices%20%26%20Data%20-%20Yahoo%20Finance.html](https://raw.githubusercontent.com/alyab16/Python-Project-for-Data-Science/cb6acd476c02df1ff74b85237a7307abf3632677/Tesla%2C%20Inc.%20(TSLA)%20Stock%20Historical%20Prices%20%26%20Data%20-%20Yahoo%20Finance.html).

In [31]:
url = "https://raw.githubusercontent.com/alyab16/Python-Project-for-Data-Science/cb6acd476c02df1ff74b85237a7307abf3632677/Tesla%2C%20Inc.%20(TSLA)%20Stock%20Historical%20Prices%20%26%20Data%20-%20Yahoo%20Finance.html"
data  = requests.get(url).text

In [32]:
soup = BeautifulSoup(data, 'html5lib')
tesla_data = pd.DataFrame(columns=["Date", "Open", "High", "Low", "Close", "Volume"])

In [33]:
# First we isolate the body of the table which contains all the information
# Then we loop through each row and find all the column values for each row
for row in soup.find("tbody").find_all('tr'):
    col = row.find_all("td")
    date = col[0].text
    Open = col[1].text
    high = col[2].text
    low = col[3].text
    close = col[4].text
    adj_close = col[5].text
    volume = col[6].text
    
    # Finally we append the data of each row to the table
    tesla_data = tesla_data.append({"Date":date, "Open":Open, "High":high, "Low":low, "Close":close, "Adj Close":adj_close, "Volume":volume}, ignore_index=True)

In [34]:
tesla_data.head()

           Date    Open    High     Low   Close       Volume Adj Close
0  Feb 08, 2024  189.00  191.62  185.58  189.34   63,994,485    189.34
1  Feb 07, 2024  188.18  189.79  182.68  187.58  111,369,800    187.58
2  Feb 06, 2024  177.21  186.49  177.11  185.10  122,676,000    185.10
3  Feb 05, 2024  184.26  184.68  175.01  181.06  134,294,400    181.06
4  Feb 02, 2024  185.04  188.69  182.00  187.91  110,505,100    187.91

# Extracting data using `pandas` library

In [35]:
read_html_pandas_data = pd.read_html(url)
read_html_pandas_data = pd.read_html(str(soup))
tesla_dataframe = read_html_pandas_data[0]
tesla_dataframe.head()

           Date    Open    High     Low  Close* Adj Close**     Volume
0  Feb 08, 2024  189.00  191.62  185.58  189.34      189.34   63994485
1  Feb 07, 2024  188.18  189.79  182.68  187.58      187.58  111369800
2  Feb 06, 2024  177.21  186.49  177.11  185.10      185.10  122676000
3  Feb 05, 2024  184.26  184.68  175.01  181.06      181.06  134294400
4  Feb 02, 2024  185.04  188.69  182.00  187.91      187.91  110505100